"""机构表增加短信运营商字段

Revision ID: 1281e11af6af
Revises: 7bc8bf24e9ef
Create Date: 2025-10-25 11:15:34.647235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1281e11af6af'
down_revision = '7bc8bf24e9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('msgorg', sa.Column('sms_expiration_date', sa.DateTime(), nullable=True))
    op.add_column('msgorg', sa.Column('sms_operator', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('msgorg', 'sms_operator')
    op.drop_column('msgorg', 'sms_expiration_date')
    # ### end Alembic commands ###
