"""add seq

Revision ID: 2febb304d0e8
Revises: b6be05fc298b
Create Date: 2020-04-13 23:34:57.888025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2febb304d0e8'
down_revision = 'b6be05fc298b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskqueue', sa.Column('queue_no', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_taskqueue_queue_no'), 'taskqueue', ['queue_no'], unique=False)
    op.drop_index('ix_taskqueue_reference_id', table_name='taskqueue')
    op.drop_column('taskqueue', 'reference_id')
    op.execute("create sequence some_no_seq start with 10000000 maxvalue 99999999 minvalue 10000000 "
               "increment by 1 cycle")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskqueue', sa.Column('reference_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index('ix_taskqueue_reference_id', 'taskqueue', ['reference_id'], unique=False)
    op.drop_index(op.f('ix_taskqueue_queue_no'), table_name='taskqueue')
    op.drop_column('taskqueue', 'queue_no')
    op.execute(sa.schema.DropSequence(sa.Sequence("some_no_seq")))
    # ### end Alembic commands ###
