"""add org and class table

Revision ID: 39539711ae27
Revises: 76dd0bc2b59a
Create Date: 2020-04-16 16:09:41.842838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39539711ae27'
down_revision = '76dd0bc2b59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msgclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('send_class', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msgorg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_code', sa.String(length=256), nullable=True),
    sa.Column('org_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messagelog', sa.Column('msg_status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messagelog', 'msg_status')
    op.drop_table('msgorg')
    op.drop_table('msgclass')
    # ### end Alembic commands ###
