"""empty message

Revision ID: 74d228b27822
Revises: 627bb33278e2
Create Date: 2020-04-12 10:48:20.426801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d228b27822'
down_revision = '627bb33278e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###
