"""add column

Revision ID: 76dd0bc2b59a
Revises: 2febb304d0e8
Create Date: 2020-04-15 21:35:45.826012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dd0bc2b59a'
down_revision = '2febb304d0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messagelog', sa.Column('mtq_stime', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messagelog', 'mtq_stime')
    # ### end Alembic commands ###
