"""empty message

Revision ID: 7bc8bf24e9ef
Revises: 39539711ae27
Create Date: 2020-09-23 10:43:40.330026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc8bf24e9ef'
down_revision = '39539711ae27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messagelog_mobile'), 'messagelog', ['mobile'], unique=False)
    op.create_index(op.f('ix_messagelog_mt_taskid'), 'messagelog', ['mt_taskid'], unique=False)
    op.create_index(op.f('ix_taskqueue_run_batch'), 'taskqueue', ['run_batch'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskqueue_run_batch'), table_name='taskqueue')
    op.drop_index(op.f('ix_messagelog_mt_taskid'), table_name='messagelog')
    op.drop_index(op.f('ix_messagelog_mobile'), table_name='messagelog')
    # ### end Alembic commands ###
