"""add task models

Revision ID: b6be05fc298b
Revises: 74d228b27822
Create Date: 2020-04-13 14:35:53.512135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6be05fc298b'
down_revision = '74d228b27822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskqueue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=32), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('run_batch', sa.String(length=32), nullable=True),
    sa.Column('last_handle_time', sa.DateTime(), nullable=True),
    sa.Column('last_handle_result', sa.String(length=256), nullable=True),
    sa.Column('try_amount', sa.Integer(), nullable=True),
    sa.Column('tried_amount', sa.Integer(), nullable=True),
    sa.Column('start_handle_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskqueue_created_at'), 'taskqueue', ['created_at'], unique=False)
    op.create_index(op.f('ix_taskqueue_reference_id'), 'taskqueue', ['reference_id'], unique=False)
    op.create_index(op.f('ix_taskqueue_updated_at'), 'taskqueue', ['updated_at'], unique=False)
    op.create_table('messagetask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_no', sa.String(length=32), nullable=True),
    sa.Column('apply_no', sa.String(length=256), nullable=True),
    sa.Column('org_code', sa.String(length=256), nullable=True),
    sa.Column('org_name', sa.String(length=256), nullable=True),
    sa.Column('send_class', sa.String(length=128), nullable=True),
    sa.Column('send_name', sa.String(length=256), nullable=True),
    sa.Column('msgcontent', sa.Text(), nullable=True),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.Column('receivers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messagetask_created_at'), 'messagetask', ['created_at'], unique=False)
    op.create_index(op.f('ix_messagetask_task_no'), 'messagetask', ['task_no'], unique=False)
    op.create_index(op.f('ix_messagetask_updated_at'), 'messagetask', ['updated_at'], unique=False)
    op.create_table('messagelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=True),
    sa.Column('callback_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('messagetask_id', sa.Integer(), nullable=True),
    sa.Column('task_no', sa.String(length=32), nullable=True),
    sa.Column('apply_no', sa.String(length=256), nullable=True),
    sa.Column('org_code', sa.String(length=256), nullable=True),
    sa.Column('org_name', sa.String(length=256), nullable=True),
    sa.Column('send_class', sa.String(length=128), nullable=True),
    sa.Column('send_name', sa.String(length=256), nullable=True),
    sa.Column('msgcontent', sa.Text(), nullable=True),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.String(length=256), nullable=True),
    sa.Column('org_form_no', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('id_no', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=128), nullable=True),
    sa.Column('mt_code', sa.String(length=30), nullable=True),
    sa.Column('mt_msg', sa.String(length=256), nullable=True),
    sa.Column('mt_taskid', sa.String(length=50), nullable=True),
    sa.Column('mtq_code', sa.String(length=128), nullable=True),
    sa.Column('mtq_msg', sa.String(length=256), nullable=True),
    sa.Column('mtq_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['messagetask_id'], ['messagetask.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messagelog_created_at'), 'messagelog', ['created_at'], unique=False)
    op.create_index(op.f('ix_messagelog_org_code'), 'messagelog', ['org_code'], unique=False)
    op.create_index(op.f('ix_messagelog_send_class'), 'messagelog', ['send_class'], unique=False)
    op.create_index(op.f('ix_messagelog_task_no'), 'messagelog', ['task_no'], unique=False)
    op.create_index(op.f('ix_messagelog_updated_at'), 'messagelog', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messagelog_updated_at'), table_name='messagelog')
    op.drop_index(op.f('ix_messagelog_task_no'), table_name='messagelog')
    op.drop_index(op.f('ix_messagelog_send_class'), table_name='messagelog')
    op.drop_index(op.f('ix_messagelog_org_code'), table_name='messagelog')
    op.drop_index(op.f('ix_messagelog_created_at'), table_name='messagelog')
    op.drop_table('messagelog')
    op.drop_index(op.f('ix_messagetask_updated_at'), table_name='messagetask')
    op.drop_index(op.f('ix_messagetask_task_no'), table_name='messagetask')
    op.drop_index(op.f('ix_messagetask_created_at'), table_name='messagetask')
    op.drop_table('messagetask')
    op.drop_index(op.f('ix_taskqueue_updated_at'), table_name='taskqueue')
    op.drop_index(op.f('ix_taskqueue_reference_id'), table_name='taskqueue')
    op.drop_index(op.f('ix_taskqueue_created_at'), table_name='taskqueue')
    op.drop_table('taskqueue')
    # ### end Alembic commands ###
